### ISSUE TITLE
Use policies

### ISSUE THREAD

**Issue by duxet** [Strimoid/Strimoid#16]
http://laravel.com/docs/5.1/authorization

**Comment by d33tah** [comment]
Could you comment on the issue?

**Comment by duxet** [comment]
At the moment most of the authorization code is placed in models, but i think that using new [Laravel policies](http://laravel.com/docs/5.1/authorization#policies) would be a better solution.

**Comment by d33tah** [comment]
Thanks for clarifying. Why would that be a better solution? Is this because the code would be cleaner?

**Comment by duxet** [comment]
Exactly. That's not really important at the moment, however it would be cool to get rid of that stuff from models in future.
