### ISSUE TITLE
Switch to CommonMark

### ISSUE THREAD

**Issue by duxet** [Strimoid/Strimoid#7]
https://github.com/thephpleague/commonmark

Additional tasks:
- [ ] Add emoji support
- [ ] Add new mention types: @op, @up, @mod, @dev

**Comment by d33tah** [comment]
What would be the benefits?

**Comment by duxet** [comment]
@d33tah: the current implementation has a few flaws, and adding features that i mentioned as subtasks would be a way easier (and cleaner) with php league commonmark parser
